name: Node.js CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install-and-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit
